AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ClusterName:
    Type: String
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String
  SecurityGroup:
    Type: String
  MyVPC:
    Type: String
  ALBPublic:
    Type: String
  ALBPrivateName:
    Type: String

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AWS::StackName}
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Image: mahfuz93/aws:greetme1.2-SNAPSHOT
          Name: Greetme
          PortMappings:
            - ContainerPort: 8082
          Cpu: 10
          Memory: 500
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Ref AWS::StackName
          Environment:
            - Name: NAME_PATH
              Value: !Join ['', ["http://", !Ref 'ALBPrivateName', ":8081"]]
            - Name: HELLO_PATH
              Value: !Join ['', ["http://", !Ref 'ALBPrivateName', ":8080"]]
      Cpu: 256
      Memory: 1GB
      NetworkMode: awsvpc
      ExecutionRoleArn: arn:aws:iam::872402760125:role/ecsTaskExecutionRole
      RequiresCompatibilities:
        - "FARGATE"
  Service:
    Type: AWS::ECS::Service
    DependsOn: Listener
    Properties:
      Cluster: !Ref ClusterName
      DesiredCount: 1
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerPort: 8082
          ContainerName: Greetme
          TargetGroupArn: !Ref TargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref SecurityGroup
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2
      TaskDefinition: !Ref TaskDefinition
      ServiceName: Greetme
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 60
      UnhealthyThresholdCount: 2
      HealthCheckPath: /
      Name: Greetme
      Port: 8082
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref MyVPC
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ALBPublic
      Port: 80
      Protocol: HTTP